In [1]:
#import resource
import gc
import json
import boto3
import decimal 
import pandas as pd 
import rope
import numpy as np
from boto3.dynamodb.conditions import Key, Attr

#parameters config
AWS_ACCESS_ID='AKIAIAE4ZHJYNQSTJS3A'
AWS_ACCESS_KEY='4miq8EXXmAe5GNkxJf+jeyhT3r1Ftum5w5pSR9LY'
TABLE_NAME='A0195017E'
REGION_NAME='ap-southeast-1'

#create service
client=boto3.client('dynamodb',region_name=REGION_NAME,aws_access_key_id=AWS_ACCESS_ID,aws_secret_access_key=AWS_ACCESS_KEY)
dynamodb=boto3.resource('dynamodb',region_name=REGION_NAME,aws_access_key_id=AWS_ACCESS_ID,aws_secret_access_key=AWS_ACCESS_KEY)

#scan table
class DDB2JSON(json.JSONEncoder): 
    def default(self, o):
        if isinstance(o,decimal.Decimal): 
            if o%1>0:
                return float(o) 
            else:
                return int(o)
        return super(DDB2JSON,self).default(o)   
table=dynamodb.Table(TABLE_NAME)
response=table.scan()
item=[]
for i in response['Items']: 
    item.append(json.dumps(i,cls=DDB2JSON))                                  
while 'LastEvaluatedKey' in response:
    response=table.scan(ExclusiveStartKey=response['LastEvaluatedKey'])
    for j in response['Items']:
        item.append(json.dumps(j,cls=DDB2JSON))

#display 
m=1
msg=pd.DataFrame()
for n in item:
    msg=msg.append(pd.DataFrame(json.loads(n),index=[m]))
    m+=1
msg.head(100)

,sensor21,sensor20,sensor18,id,sensor19,sensor16,sensor17,sensor14,sensor15,sensor12,...,sensor6,sensor5,Matric No.,sensor4,sensor3,sensor9,sensor8,sensor7,sensor2,sensor1
1,23.4190,39.06,2388,FD001_1,100,0.03,392,8138.62,8.4195,521.66,...,21.61,14.62,A0195017E,1400.60,1589.70,9046.19,2388.06,554.36,641.82,518.67
2,23.4236,39.00,2388,FD001_1,100,0.03,392,8131.49,8.4318,522.28,...,21.61,14.62,A0195017E,1403.14,1591.82,9044.07,2388.04,553.75,642.15,518.67
3,23.3442,38.95,2388,FD001_1,100,0.03,390,8133.23,8.4178,522.42,...,21.61,14.62,A0195017E,1404.20,1587.99,9052.94,2388.08,554.26,642.35,518.67
4,23.3739,38.88,2388,FD001_1,100,0.03,392,8133.83,8.3682,522.86,...,21.61,14.62,A0195017E,1401.87,1582.79,9049.48,2388.11,554.45,642.35,518.67
5,23.4044,38.90,2388,FD001_1,100,0.03,393,8133.80,8.4294,522.19,...,21.61,14.62,A0195017E,1406.22,1582.85,9055.15,2388.06,554.00,642.37,518.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,23.3255,38.88,2388,FD001_1,100,0.03,392,8130.69,8.4311,521.66,...,21.61,14.62,A0195017E,1395.16,1584.07,9048.71,2388.07,553.34,642.19,518.67
97,23.2963,39.01,2388,FD001_1,100,0.03,392,8128.74,8.4105,521.67,...,21.61,14.62,A0195017E,1407.81,1595.77,9046.10,2388.09,553.40,642.07,518.67
98,23.2554,38.96,2388,FD001_1,100,0.03,391,8127.89,8.4012,522.31,...,21.61,14.62,A0195017E,1404.56,1591.11,9045.49,2388.06,552.75,642.00,518.67
99,23.2323,38.82,2388,FD001_1,100,0.03,393,8131.77,8.4481,521.42,...,21.61,14.62,A0195017E,1406.13,1592.73,9045.14,2388.08,553.76,642.46,518.67
100,23.4090,38.93,2388,FD001_1,100,0.03,392,8132.49,8.4241,521.55,...,21.61,14.62,A0195017E,1411.35,1589.63,9045.72,2388.07,554.22,642.22,518.67